# Generated by Django 2.2 on 2020-03-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0003_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user_likes',
            field=models.ManyToManyField(related_name='likes', to='appOne.User'),
        ),
    ]
